baseURL = "https://blog.devquantum.xyz"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Quantum0x | Web3 UX Engineer"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
name = "Quantum 0x"

[params]
author = "Quantum 0x"
description = "Web3 UX Engineer"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = false

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional
  

[[params.social]]
id = "github"
url = "https://github.com/quantum-0x"

[[params.social]]
id = "telegram"
url = "https://t.me/quantum0x"

[[params.social]]
id = "email"
url = "mailto:helloquantum0x@gmail.com"

[markup.goldmark.renderer]
unsafe = true
